### ISSUE TITLE
CapicomEncrypted class

### ISSUE THREAD

**Issue by gsugambit** [creepid/capicom-wrapper#3]
I am trying to use this as a dependency but for some reason the jar file inside of your repo does not contain all of your class files. 
If you open the jar, you will see the CapicomEncrypted class is not included. I was trying to reference it in my project when I noticed it could not be imported :(

**Comment by gsugambit** [comment]
![image](https://user-images.githubusercontent.com/13861767/36932573-5e6299a8-1e90-11e8-8646-c60027cd6828.png)

**Comment by rusakovichma** [comment]
Fixed.
Please, download the last jar: https://github.com/creepid/capicom-wrapper/releases/download/0.2/capicom-wrapper-0.2.jar and add it to your project,
or use as in examples: https://github.com/creepid/capicom-wrapper-examples
